### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CelerSan** [termux/proot-distro#391]
### Problem description

Hi guys, i installed a Proot-distro (Debian) on my Termux with xfce4 interface on Termux-x11 and install Pulseaudio on Termux as on the Distro, everything works fine of course the Distro the sound the interface everything is perfect but on the Termux side there is a sequence of the same and displays the same error message continually and those even after closing the Distro and Termux-x11 (by forcing the stop)

 Here is the message in question:

java.net.SocketException: Socket closed

at java.net. PlainSocketImpl.socketAccept(PlainSocketImpl.java:213)

at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java: 451)

at java.net.ServerSocket.implAccept(ServerSocket.java:569)

at java.net.ServerSocket.accept(ServerSocket.java:537) at com.termux.x11.CmdEntryPoint. lambdasspawnListening

Thread$1(CmdEntryPoint.java:130) com.termux.x11. CadEntryPoint.$r85lambda$vk4R0aNTM8gv2nUkB-fFZSrf_IY(CmdEntryPoint.java:0)

at at com.termux.x11.CndEntryPoint$$ExternalSyntheticLambdal.run(RUSSSyntheticClass:0)

at java.lang.Thread.run(Thread.java:1012)

And the Distro launch script (if that helps):

kill -9 $(pgrep -f "termux.x11") 2>/dev/null

pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit>

export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :0 >/dev/null &

sleep 3

am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1

proot-distro login debian --shared-tmp -- /bin/bash -c  'export PULSE_SERVER=127.0.0.1 && pulseaudio>

exit 0

PS: don't pay attention to the thing at the bottom right

### What steps will reproduce the bug?

![Screenshot_20240128-145155](https://github.com/termux/proot-distro/assets/144831071/9ad2d9e6-a47a-487b-8742-615407a39702)

**Comment by twaik** [comment]
I am not sure if it is a termux-x11 error. May be proot-related
