### ISSUE TITLE
[Bug]: Error: uv_interface_addresses returned unknow

### ISSUE THREAD

**Issue by Risik34** [termux/proot-distro#456]
### Problem description

 Getting this error when running vite or any other web server  in host mode 

pnpm run dev --host

> testsite@0.0.0 dev /home/risi/repos/testsite
> vite "--host"

error when starting dev server:                                          SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
    at Object.networkInterfaces (node:os:277:16)                             at resolveServerUrls (file:///home/risi/repos/testsite/node_modules/.pnpm/vite@5.4.9/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:17353:24)                                                                          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                     at async Object.listen (file:///home/risi/repos/testsite/node_modules/.pnpm/vite@5.4.9/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:62868:31)                                                                        at async CAC.<anonymous> (file:///home/risi/repos/testsite/node_modules/.pnpm/vite@5.4.9/node_modules/vite/dist/node/cli.js:748:5)
 ELIFECYCLE  Command failed with exit code 1.

### What steps will reproduce the bug?

To reproduce the error run a vite server in ubuntu 

### What is the expected behavior?

It's expected to host so that others machines can access it

**Comment by twaik** [comment]
Issue template specifies it pretty much clear.

> [!IMPORTANT]  
> This is a bug tracker of the PRoot Distro - a Bash script utility for managing distribution rootfs for use with PRoot.
>
> !!! DO NOT REPORT ISSUES ABOUT NETWORKING, CRASHES, BLACK SCREENS, BROKEN WINE AND SO ON. THEY WILL BE IGNORED !!! Only bugs related to proot-distro shell script implementation will be accepted.
